### PR TITLE
Added Support for ul and ol and added syntax to the docs

### PR DESCRIPTION
**Pull request by nmacarthur**
# Description

Added support for ul and ol following the format
ul (or ol) :: listItem * listItem * ...

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Yamboy1** [comment]
you might be better off making this into a nestable style tag (see DOCS.md) for consistency with the current div tag, and the ability to add style etc to list items

**Comment by Yamboy1** [comment]
@ntrupin your thoughts?

**Comment by nmacarthur** [comment]
Thanks for the feedback!
I'll see if I can make it nestable!

**Comment by nmacarthur** [comment]
@ntrupin I've made those changes and edited the docs, is that what you were after?

**Comment by ntrupin** [comment]
Yes, thank you. Because of merge conflicts with the new version of the compiler, I cannot directly merge them here. I will add the changes directly to the compiler and accredit you in the update log.

**Pull request closed without merging**
